Resources:
  # Création d'un groupe de sécurité pour permettre l'accès à la base de données Aurora
  DBSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      GroupDescription: "Allow access to the Aurora DB cluster"
      DBSecurityGroupIngress:
        - CIDRIP: "0.0.0.0/0" # Permettre l'accès depuis n'importe où (à modifier en fonction de vos besoins)
          FromPort: "3306"
          ToPort: "3306"

  # Création du cluster de base de données Aurora
  AuroraDBCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      Engine: "aurora"
      MasterUsername: "admin"
      MasterUserPassword: "MySecurePassword"
      DatabaseName: "MyDatabase"
      BackupRetentionPeriod: 7 # Nombre de jours de rétention des sauvegardes
      StorageEncrypted: true # Chiffrement au repos
      VpcSecurityGroupIds:
        - Ref: DBSecurityGroup
      Tags:
        - Key: Name
          Value: "MyAuroraDBCluster"

  # Création d'un groupe de paramètres de cluster pour activer le chiffrement au repos
  AuroraDBClusterParameterGroup:
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties:
      Description: "Parameter group to enable encryption at rest for Aurora cluster"
      Family: "aurora-mysql5.7"
      Parameters:
        binlog_encryption: "ON"
        binlog_format: "ROW"

  # Création d'une instance de base de données Aurora (noeud)
  AuroraDBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref AuroraDBCluster
      Engine: "aurora"
      DBInstanceClass: "db.r5.large" # Type d'instance Aurora
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: "MyAuroraDBInstance"