# Generated by Django 5.0.4 on 2024-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemViewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="categorie",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.IntegerField(
                default=1, primary_key=True, serialize=False
            ),
        ),
    ]
