# Generated by Django 5.0.4 on 2024-05-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemViewer", "0002_item_categorie_item_name_alter_item_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="id",
            new_name="ankama_id",
        ),
        migrations.AddField(
            model_name="item",
            name="ap_cost",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="condition_tree",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="conditions",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="critical_hit_bonus",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="critical_hit_probability",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name="item",
            name="effects",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="image_urls",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="is_two_handed",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="is_weapon",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="level",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="max_cast_per_turn",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="parent_set",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="pods",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="range",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="recipe",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
