# Generated by Django 5.0.4 on 2024-05-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemViewer", "0003_rename_id_item_ankama_id_item_ap_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ap_cost",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
