# Generated by Django 5.0.4 on 2024-05-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemViewer", "0004_alter_item_ap_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ap_cost",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
