# Generated by Django 5.0.4 on 2024-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itemViewer", "0005_alter_item_ap_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ap_cost",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="condition_tree",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="critical_hit_bonus",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="critical_hit_probability",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_two_handed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="max_cast_per_turn",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="parent_set",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="range",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
