# Generated by Django 5.0.4 on 2024-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "itemViewer",
            "0006_alter_item_ap_cost_alter_item_condition_tree_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="conditions",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="effects",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_weapon",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="pods",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="recipe",
            field=models.JSONField(default=None, null=True),
        ),
    ]
