# Generated by Django 5.0.4 on 2024-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="random", max_length=100)),
                ("level", models.IntegerField(default=None)),
                ("server", models.CharField(max_length=100)),
                (
                    "character_class",
                    models.CharField(default="iop", max_length=100),
                ),
            ],
        ),
    ]
