# Generated by Django 5.0.4 on 2024-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="character",
            name="updated_at",
        ),
    ]
