# Generated by Django 5.0.4 on 2024-05-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterclass",
            name="name",
            field=models.CharField(
                default="random", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]