# Generated by Django 5.0.4 on 2024-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="random", max_length=100, unique=True
                    ),
                ),
                (
                    "logo_url",
                    models.CharField(default="random", max_length=100),
                ),
            ],
        ),
    ]
