# Generated by Django 5.0.4 on 2024-05-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0002_character_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClass",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="random", max_length=100)),
                (
                    "logo_url",
                    models.CharField(default="random", max_length=100),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="characterManager.characterclass",
            ),
        ),
    ]
