# Generated by Django 5.0.4 on 2024-05-15 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characterManager",
            "0002_alter_characterclass_name_alter_server_name",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddField(
            model_name="caracteristiquesetclass",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]