# Generated by Django 5.0.4 on 2024-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characterManager",
            "0003_characterclass_alter_character_character_class",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="character_class",
        ),
        migrations.AlterField(
            model_name="character",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
