# Generated by Django 5.0.4 on 2024-05-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characterManager",
            "0004_remove_character_character_class_alter_character_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="characterManager.characterclass",
            ),
            preserve_default=False,
        ),
    ]
