# Generated by Django 5.0.4 on 2024-05-18 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0004_caracteristiquesetclass"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaracteristiqueSetClass",
            new_name="CaracteristiqueSet",
        ),
    ]
