# Generated by Django 5.0.4 on 2024-05-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0005_character_character_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaracteristiqueSetClass",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("sagesse", models.IntegerField(default=0)),
                ("agilite", models.IntegerField(default=0)),
                ("intelligence", models.IntegerField(default=0)),
                ("chance", models.IntegerField(default=0)),
                ("force", models.IntegerField(default=0)),
                (
                    "character_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characterManager.character",
                    ),
                ),
            ],
        ),
    ]
