# Generated by Django 5.0.4 on 2024-05-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0006_caracteristiquesetclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="caracteristiquesetclass",
            name="vitalite",
            field=models.IntegerField(default=0),
        ),
    ]
