# Generated by Django 5.0.4 on 2024-05-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characterManager", "0006_stuffset"),
        (
            "itemViewer",
            "0007_alter_item_conditions_alter_item_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="character_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="characterManager.characterclass",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="characterManager.server",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="anneau_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_anneau_1",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="anneau_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_anneau_2",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="arme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_arme",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="botte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_botte",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="bouclier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_bouclier",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="ceinture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_ceinture",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="chapeau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_chapeau",
                to="itemViewer.item",
            ),
        ),
        migrations.AlterField(
            model_name="stuffset",
            name="collier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stuffset_collier",
                to="itemViewer.item",
            ),
        ),
    ]
